# Generated by Django 4.2.30 on 2026-04-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParacletePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The prompt text shown to the user')),
                ('pathway', models.CharField(choices=[('new_life', 'New Life'), ('spiritual_formation', 'Spiritual Formation'), ('community_life', 'Community Life'), ('service', 'Service'), ('leadership', 'Leadership'), ('learning', 'Learning'), ('mission', 'Mission'), ('apostolic_stewardship', 'Apostolic Stewardship')], help_text='KGS pathway this prompt relates to', max_length=30)),
                ('min_level', models.IntegerField(default=0, help_text='Minimum competence level to receive this prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pathway', 'min_level'],
            },
        ),
    ]
