# Generated by Django 5.2.13 on 2026-04-28 12:39

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_avatar_url_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss'), ('dr', 'Dr'), ('prof', 'Prof'), ('rev', 'Rev'), ('pastor', 'Pastor')], max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('id_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('member_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('education', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('gifts_skills', models.TextField(blank=True)),
                ('accepted_christ', models.BooleanField(null=True)),
                ('church_member', models.BooleanField(null=True)),
                ('church_name', models.CharField(blank=True, max_length=255)),
                ('referee_1_name', models.CharField(blank=True, max_length=255)),
                ('referee_2_name', models.CharField(blank=True, max_length=255)),
                ('referee_letter_1', models.FileField(blank=True, null=True, upload_to='referee-letters/')),
                ('referee_letter_2', models.FileField(blank=True, null=True, upload_to='referee-letters/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_userprofile',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='induction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='induction_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='induction_pathway',
            field=models.CharField(blank=True, choices=[('reconditioning', 'Reconditioning'), ('beginners', 'Beginners')], max_length=20, null=True),
        ),
    ]
