# Generated by Django 5.2.13 on 2026-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_tenant_logo_url_tenant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tier',
            field=models.CharField(choices=[('handbook', 'Handbook'), ('induction', 'Induction'), ('church_node', 'Church Node'), ('church_collective', 'Church Collective'), ('district', 'District'), ('provincial', 'Provincial'), ('national', 'National'), ('regional', 'Regional'), ('continental', 'Continental'), ('global', 'Global')], max_length=30),
        ),
    ]
