# Generated by Django 5.2.13 on 2026-04-28 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_induction_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('domain', models.CharField(max_length=120)),
                ('office', models.CharField(max_length=120)),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenants_serviceorder',
                'ordering': ['order_number'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
    ]
