# Generated by Django 5.2.13 on 2026-05-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_coordinator_and_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='area_of_operation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='community_theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
