# Generated by Django 5.2.13 on 2026-04-16 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("membership_approved", "Membership Approved"),
                            ("membership_denied", "Membership Denied"),
                            ("activity_assigned", "Activity Assigned"),
                            ("activity_completed", "Activity Completed"),
                            ("lesson_completed", "Lesson Completed"),
                            ("certification_earned", "Certification Earned"),
                            ("announcement", "Community Announcement"),
                            ("mandate_published", "Mandate Published"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_47e85c_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_c62b26_idx",
                    ),
                ],
            },
        ),
    ]
