# Generated by Django 5.2.13 on 2026-04-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('membership_approved', 'Membership Approved'), ('membership_denied', 'Membership Denied'), ('activity_assigned', 'Activity Assigned'), ('activity_completed', 'Activity Completed'), ('lesson_completed', 'Lesson Completed'), ('certification_earned', 'Certification Earned'), ('level_advanced', 'Level Advanced'), ('induction_completed', 'Induction Completed'), ('announcement', 'Community Announcement'), ('mandate_published', 'Mandate Published'), ('tenant_invitation', 'Community Invitation'), ('member_added', 'Added to Community'), ('member_removed', 'Removed from Community'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
