# Generated by Django 5.2.13 on 2026-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
