# Generated by Django 4.2.30 on 2026-06-18 17:06

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
    ]
