# Generated by Django 4.2.30 on 2026-06-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('membership_approved', 'Membership Approved'), ('membership_denied', 'Membership Denied'), ('activity_assigned', 'Activity Assigned'), ('activity_completed', 'Activity Completed'), ('lesson_completed', 'Lesson Completed'), ('certification_earned', 'Certification Earned'), ('level_advanced', 'Level Advanced'), ('induction_completed', 'Induction Completed'), ('announcement', 'Community Announcement'), ('mandate_published', 'Mandate Published'), ('tenant_invitation', 'Community Invitation'), ('member_added', 'Added to Community'), ('member_removed', 'Removed from Community'), ('support_request_created', 'Support Request Created'), ('support_request_acknowledged', 'Support Request Acknowledged'), ('live_request_raised', 'Live Request Raised'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
