# Generated by Django 4.2 on 2026-04-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_class', models.CharField(choices=[('personal', 'Personal'), ('organizational', 'Organizational'), ('governance', 'Governance')], max_length=20)),
                ('record_family', models.CharField(choices=[('journal', 'Journal'), ('governance', 'Governance'), ('activity', 'Activity'), ('learning', 'Learning'), ('reference', 'Reference'), ('bible', 'Bible'), ('community', 'Community')], max_length=20)),
                ('record_type', models.CharField(max_length=50)),
                ('origin', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('paraclete', 'Paraclete'), ('import', 'Import')], default='user', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived'), ('locked', 'Locked')], default='active', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('permissions_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='records.record')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='records.record')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'records_record',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('directed', 'Directed'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('relationship_type', models.CharField(choices=[('relates_to', 'Relates To'), ('derived_from', 'Derived From'), ('references', 'References'), ('answers', 'Answers'), ('fulfills', 'Fulfills'), ('requests', 'Requests'), ('has_symbol', 'Has Symbol'), ('matches_pattern', 'Matches Pattern'), ('assigned_to', 'Assigned To'), ('tracks', 'Tracks'), ('completes', 'Completes'), ('part_of', 'Part Of'), ('aligns_with', 'Aligns With'), ('authorised_by', 'Authorised By'), ('has_subject', 'Has Subject'), ('has_entity', 'Has Entity'), ('tagged_in', 'Tagged In')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('strength', models.CharField(blank=True, choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='records.record')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('to_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='records.record')),
            ],
            options={
                'db_table': 'records_relationship',
            },
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_record'], name='records_rel_from_re_4201d6_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['to_record'], name='records_rel_to_reco_2073d7_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['relationship_type'], name='records_rel_relatio_22f583_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['tenant'], name='records_rec_tenant__7ae6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['record_family'], name='records_rec_record__44e0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['record_type'], name='records_rec_record__36af4b_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['record_class'], name='records_rec_record__fe7ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_by'], name='records_rec_created_7081fd_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_at'], name='records_rec_created_85482c_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['status'], name='records_rec_status_4b157d_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['tenant', 'record_family'], name='records_rec_tenant__1503d4_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['tenant', 'record_class'], name='records_rec_tenant__7e8482_idx'),
        ),
    ]
