# Generated by Django 5.2.13 on 2026-05-17 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncChangelog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('changed_at', models.DateTimeField(db_index=True)),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_sync_changelog',
                'ordering': ['changed_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_sync_c_entity__27db15_idx'), models.Index(fields=['changed_at'], name='core_sync_c_changed_b3db4d_idx'), models.Index(fields=['synced_at'], name='core_sync_c_synced__883e2b_idx')],
            },
        ),
    ]
