# Generated by Django 4.2.30 on 2026-06-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bootstrapped_at', models.DateTimeField(blank=True, null=True)),
                ('bootstrap_version', models.CharField(blank=True, default='', max_length=20)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('mandate_access_level', models.IntegerField(default=4)),
                ('keys_access_level', models.IntegerField(default=4)),
                ('reference_access_level', models.IntegerField(default=3)),
                ('bootstrapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_platform_config',
            },
        ),
    ]
