# Generated by Django 5.2.13 on 2026-05-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationconfirmation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
