# Generated by Django 4.2.30 on 2026-08-10 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0004_alter_certificationconfirmation_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.IntegerField(choices=[(1, 'Module 1 — Keys to the Kingdom'), (2, 'Module 2 — Repentance / Reformation'), (3, 'Module 3 — Secret to a Fulfilled Life'), (4, 'Module 4 — The Sceptre Community')])),
                ('sequence_order', models.IntegerField(unique=True)),
                ('step_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Knowledge Check Quiz'), ('module_test', 'Module Test'), ('final_test', 'Final Test')], max_length=20)),
                ('pathway', models.CharField(choices=[('all', 'All'), ('beginners', 'Beginners'), ('reconditioning', 'Reconditioning')], default='all', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='Lesson content coming soon.')),
                ('pass_score', models.IntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='InductionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learn.inductionstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InductionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learn.inductionquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InductionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('awaiting_steward', 'Awaiting Steward Confirmation')], default='locked', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learn.inductionstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='induction_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step__sequence_order'],
                'indexes': [models.Index(fields=['user', 'status'], name='learn_induc_user_id_536aad_idx')],
                'unique_together': {('user', 'step')},
            },
        ),
    ]
