# Generated by Django 4.2.30 on 2026-08-11 10:00

import core.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_relationship_sequence_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0005_induction_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('free_text', 'Free Text')], default='single_choice', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='records.record')),
            ],
            options={
                'ordering': ['order'],
            },
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learn.assessmentquestion')),
            ],
            options={
                'ordering': ['order'],
            },
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningAttachment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='learn/protected/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_attachments', to='records.record')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['record', 'order'], name='learn_learn_record__124894_idx')],
            },
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['record', 'order'], name='learn_asses_record__16f966_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentoption',
            index=models.Index(fields=['question', 'order'], name='learn_asses_questio_890224_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'record'], name='learn_asses_user_id_6b047c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['record', 'passed'], name='learn_asses_record__e7ae96_idx'),
        ),
    ]
