# Generated by Django 4.2 on 2026-04-10 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('tier', models.CharField(choices=[('handbook', 'Handbook'), ('church_node', 'Church Node'), ('church_collective', 'Church Collective'), ('district', 'District'), ('provincial', 'Provincial'), ('national', 'National'), ('regional', 'Regional'), ('continental', 'Continental'), ('global', 'Global')], max_length=30)),
                ('affiliation', models.CharField(choices=[('ichebo', 'Ichebo'), ('independent', 'Independent'), ('affiliate', 'Affiliate')], default='independent', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_collective', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('settings_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tenants', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenant',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_path', models.CharField(db_index=True, max_length=500)),
                ('role', models.CharField(choices=[('seeker', 'Seeker'), ('disciple', 'Disciple'), ('branch-steward', 'Branch Steward'), ('district-steward', 'District Steward'), ('provincial-steward', 'Provincial Steward'), ('national-steward', 'National Steward'), ('regional-steward', 'Regional Steward'), ('continental-steward', 'Continental Steward'), ('global-steward', 'Global Steward'), ('admin', 'Admin')], max_length=30)),
                ('level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants_userpermission',
                'unique_together': {('tenant', 'user', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['path'], name='tenants_ten_path_469337_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['tier'], name='tenants_ten_tier_9afea8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'),
        ),
    ]
