# Generated by Django 5.2.13 on 2026-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_userpermission_metadata_alter_userpermission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
