# Generated by Django 5.2.13 on 2026-05-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_community_theme_area_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
