# Generated by Django 4.2.30 on 2026-06-18 17:06

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_desktoplicence_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='desktoplicence',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='serviceorder',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tenantinvitation',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userpermission',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
    ]
