# Generated by Django 4.2.30 on 2026-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_desktoplicence_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tier',
            field=models.CharField(choices=[('handbook', 'Handbook'), ('induction', 'Induction'), ('church_node', 'Church Node'), ('church_collective', 'Church Collective'), ('local', 'Local'), ('ward', 'Ward'), ('district', 'District'), ('provincial', 'Provincial'), ('national', 'National'), ('regional', 'Regional'), ('continental', 'Continental'), ('global', 'Global')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='role',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('beginner', 'Beginner'), ('disciple', 'Disciple'), ('branch-steward', 'Branch Steward'), ('local-steward', 'Local Steward'), ('district-steward', 'District Steward'), ('provincial-steward', 'Provincial Steward'), ('national-steward', 'National Steward'), ('regional-steward', 'Regional Steward'), ('continental-steward', 'Continental Steward'), ('global-steward', 'Global Steward'), ('admin', 'Admin')], max_length=30),
        ),
    ]
