# Generated by Django 4.2.30 on 2026-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_tenant_tier_alter_userpermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tier',
            field=models.CharField(choices=[('handbook', 'Handbook'), ('induction', 'Induction'), ('church_node', 'Church Node'), ('church_collective', 'Church Collective'), ('constituency', 'Constituency'), ('ward', 'Ward'), ('district', 'District'), ('provincial', 'Provincial'), ('national', 'National'), ('regional', 'Regional'), ('continental', 'Continental'), ('global', 'Global')], max_length=30),
        ),
    ]
