# Generated by Django 4.2.30 on 2026-09-30 10:32

from django.db import migrations
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_backfill_constituency_tier'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('objects', tenants.models.TenantManager()),
            ],
        ),
    ]
