# Generated by Django 5.2.13 on 2026-04-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_orientation_record_to_tenant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="orientation_record",
        ),
    ]
