# Generated by Django 5.2.13 on 2026-04-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_orientation_record_from_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='role',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('beginner', 'Beginner'), ('disciple', 'Disciple'), ('branch-steward', 'Branch Steward'), ('district-steward', 'District Steward'), ('provincial-steward', 'Provincial Steward'), ('national-steward', 'National Steward'), ('regional-steward', 'Regional Steward'), ('continental-steward', 'Continental Steward'), ('global-steward', 'Global Steward'), ('admin', 'Admin')], max_length=30),
        ),
    ]
