# Generated by Django 5.2.13 on 2026-05-22 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0006_alter_record_deleted_at_and_more'),
        ('tenants', '0012_desktoplicence_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('stream_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('rtmp_url', models.CharField(blank=True, max_length=500)),
                ('hls_url', models.CharField(blank=True, max_length=500)),
                ('vod_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL)),
                ('gathering_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='records.record')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
