# Generated by Django 5.2.13 on 2026-04-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('records', '0003_activity_linked_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='linked_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_activities', to='records.record'),
        ),
    ]
