# Generated by Django 4.2.30 on 2026-06-18 17:06

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_managers_alter_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
    ]
