# Generated by Django 4.2.30 on 2026-04-10 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BibleTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('language_full', models.CharField(default='English', max_length=50)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('copyright_statement', models.TextField(blank=True, null=True)),
                ('is_copyright', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.biblebook')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.bibletranslation')),
            ],
            options={
                'indexes': [models.Index(fields=['translation', 'book', 'chapter'], name='bible_bible_transla_62ac79_idx'), models.Index(fields=['book', 'chapter', 'verse'], name='bible_bible_book_id_fb4fe4_idx')],
                'unique_together': {('translation', 'book', 'chapter', 'verse')},
            },
        ),
    ]
