# Generated by Django 4.2.30 on 2026-04-10 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('task', 'Task'), ('habit', 'Habit'), ('goal', 'Goal'), ('event', 'Event'), ('campaign', 'Campaign'), ('project', 'Project'), ('programme', 'Programme'), ('reminder', 'Reminder'), ('skill', 'Skill')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', max_length=10)),
                ('recurrence_rule', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('kgs_pillar', models.CharField(blank=True, choices=[('apostolic', 'Apostolic'), ('strategy', 'Strategy'), ('formation', 'Formation'), ('programmes', 'Programmes'), ('mission', 'Mission'), ('communities', 'Communities'), ('stewardship', 'Stewardship')], max_length=30, null=True)),
                ('kgs_pathway', models.CharField(blank=True, choices=[('new_life', 'New Life'), ('spiritual_formation', 'Spiritual Formation'), ('community_life', 'Community Life'), ('service', 'Service'), ('leadership', 'Leadership'), ('learning', 'Learning'), ('mission', 'Mission'), ('apostolic_stewardship', 'Apostolic Stewardship')], max_length=30, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('parent_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_activities', to='activity.activity')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('previous_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='activity.activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity'], name='activity_ac_activit_1241f8_idx'), models.Index(fields=['event_type'], name='activity_ac_event_t_687973_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['tenant'], name='activity_ac_tenant__d2a0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activity_ac_activit_b6e897_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assigned_to'], name='activity_ac_assigne_401fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='activity_ac_status_f471b6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['due_at'], name='activity_ac_due_at_b3c437_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['scheduled_at'], name='activity_ac_schedul_5b1f15_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['parent_activity'], name='activity_ac_parent__e9e070_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_by'], name='activity_ac_created_ec3f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['tenant', 'activity_type'], name='activity_ac_tenant__3747b8_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['tenant', 'assigned_to'], name='activity_ac_tenant__777055_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assigned_to', 'status'], name='activity_ac_assigne_ee12e5_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assigned_to', 'due_at'], name='activity_ac_assigne_1bc240_idx'),
        ),
    ]
