# Generated by Django 4.2.30 on 2026-06-26 15:29

import core.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0013_alter_desktoplicence_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loop_default_video_id', models.UUIDField(blank=True, null=True)),
                ('fallback_playlist', models.JSONField(blank=True, default=list)),
                ('fallback_position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_configs_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Channel Configuration',
                'verbose_name_plural': 'Channel Configurations',
            },
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSlot',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('content_type', models.CharField(choices=[('vod', 'Video on Demand'), ('live', 'Live Broadcast')], max_length=10)),
                ('video_record_id', models.UUIDField(blank=True, null=True)),
                ('broadcast_schedule_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_slots_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_slots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['tenant', 'scheduled_start', 'scheduled_end'], name='broadcast_c_tenant__303c61_idx')],
            },
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
    ]
