# Generated by Django 4.2.30 on 2026-07-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial_channel_config_and_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='loop_default_external_url',
            field=models.URLField(blank=True, help_text='Fallback to a YouTube or direct mp4 URL if no UUID is provided', null=True),
        ),
    ]
