# Generated by Django 5.2.13 on 2026-05-22 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0003_biblebook_uuid_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('branch', models.CharField(choices=[('reference', 'Reference Library'), ('mandate', 'Mandate Branch'), ('keys', 'Keys Library')], default='reference', max_length=20)),
                ('record_type', models.CharField(choices=[('class', 'Class'), ('principle', 'Principle'), ('concept', 'Concept'), ('divine_pattern', 'Divine Pattern'), ('mandate', 'Mandate'), ('statement', 'Statement'), ('framework', 'Framework'), ('narrative', 'Narrative'), ('subject', 'Subject'), ('entity', 'Entity'), ('protocol', 'Protocol'), ('procedure', 'Procedure'), ('programme', 'Programme'), ('key', 'Key')], default='principle', max_length=30)),
                ('hrs_complexity', models.CharField(blank=True, max_length=100)),
                ('hrs_relationship_position', models.CharField(blank=True, max_length=100)),
                ('hrs_position', models.CharField(blank=True, max_length=100)),
                ('hrs_direction', models.CharField(blank=True, max_length=100)),
                ('hrs_speed', models.CharField(blank=True, max_length=100)),
                ('hrs_emotional_tone', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('locked', 'Locked'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_records_created', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_records_locked', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='handbook.handbookrecord')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='handbook.handbookrecord')),
            ],
            options={
                'ordering': ['branch', 'record_type', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HandbookRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship_type', models.CharField(choices=[('part_of', 'Part Of'), ('derived_from', 'Derived From'), ('aligns_with', 'Aligns With'), ('authorised_by', 'Authorised By'), ('references', 'References'), ('has_symbol', 'Has Symbol'), ('matches_pattern', 'Matches Pattern')], default='references', max_length=30)),
                ('direction', models.CharField(choices=[('directed', 'Directed'), ('bidirectional', 'Bidirectional')], default='directed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('bible_verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handbook_references', to='bible.bibleverse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_relationships_created', to=settings.AUTH_USER_MODEL)),
                ('from_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='handbook.handbookrecord')),
                ('to_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='handbook.handbookrecord')),
            ],
            options={
                'ordering': ['relationship_type'],
            },
        ),
        migrations.CreateModel(
            name='HandbookAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('editor', 'Editor')], default='reader', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbook_access_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
