# Generated by Django 4.2.30 on 2026-04-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='bible_verse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_references', to='bible.bibleverse'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='records.record'),
        ),
    ]
