# Generated by Django 5.2.13 on 2026-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_relationship_bible_verse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('relates_to', 'Relates To'), ('derived_from', 'Derived From'), ('references', 'References'), ('answers', 'Answers'), ('fulfills', 'Fulfills'), ('requests', 'Requests'), ('has_symbol', 'Has Symbol'), ('matches_pattern', 'Matches Pattern'), ('assigned_to', 'Assigned To'), ('tracks', 'Tracks'), ('completes', 'Completes'), ('part_of', 'Part Of'), ('aligns_with', 'Aligns With'), ('authorised_by', 'Authorised By'), ('has_subject', 'Has Subject'), ('has_entity', 'Has Entity'), ('tagged_in', 'Tagged In'), ('community_ref', 'Community Reference')], max_length=30),
        ),
    ]
