# Generated by Django 5.2.13 on 2026-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibletranslation',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
