# Generated by Django 5.2.13 on 2026-04-27 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_widen_year_field'),
        ('records', '0003_activity_linked_record'),
        ('tenants', '0004_userpermission_metadata_alter_userpermission_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['bible_verse'], name='records_rel_bible_v_e44e73_idx'),
        ),
    ]
