# Generated by Django 4.2.30 on 2026-06-18 17:06

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_record_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='record',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
                ('objects', core.managers.SoftDeleteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('active', 'Active'), ('locked', 'Locked'), ('completed', 'Completed'), ('archived', 'Archived'), ('superseded', 'Superseded')], default='active', max_length=20),
        ),
    ]
