# Generated by Django 4.2.30 on 2026-08-11 10:00

from django.db import migrations, models


def backfill_curriculum_order(apps, schema_editor):
    """Give existing curriculum edges a stable 1..n order.

    Everything sorted by Record.created_at before this field existed, so that
    is the order learners already see — preserve it rather than inventing one.
    Only learning-family part_of edges are touched; every other relationship
    keeps 0, which nothing reads.
    """
    Relationship = apps.get_model('records', 'Relationship')

    edges = (
        Relationship.objects
        .filter(
            relationship_type='part_of',
            deleted_at__isnull=True,
            to_record__isnull=False,
            from_record__record_family='learning',
        )
        .select_related('from_record')
        .order_by('to_record_id', 'from_record__created_at')
    )

    current_parent, position, updates = None, 0, []
    for edge in edges:
        if edge.to_record_id != current_parent:
            current_parent, position = edge.to_record_id, 0
        position += 1
        edge.sequence_order = position
        updates.append(edge)

    if updates:
        Relationship.objects.bulk_update(updates, ['sequence_order'], batch_size=500)


def unset_curriculum_order(apps, schema_editor):
    apps.get_model('records', 'Relationship').objects.update(sequence_order=0)


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_managers_alter_relationship_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='sequence_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['to_record', 'relationship_type', 'sequence_order'], name='records_rel_to_reco_1821d3_idx'),
        ),
        migrations.RunPython(backfill_curriculum_order, unset_curriculum_order),
    ]
