# Generated by Django 4.2.30 on 2026-04-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_record_id', models.UUIDField(db_index=True)),
                ('learner_id', models.UUIDField(db_index=True)),
                ('previous_competence_level', models.IntegerField()),
                ('new_competence_level', models.IntegerField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'indexes': [models.Index(fields=['certification_record_id'], name='learn_certi_certifi_cd3cd7_idx'), models.Index(fields=['learner_id'], name='learn_certi_learner_34c71e_idx'), models.Index(fields=['confirmed_by'], name='learn_certi_confirm_d7af0a_idx')],
            },
        ),
    ]
